version: '3'
services:
  nacos:
    image: nacos/nacos-server:2.0.3-slim
    restart: always
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    container_name: postgres
  etcd:
    image: quay.io/coreos/etcd:v3.5.4
    restart: always
    command: >
      /usr/local/bin/etcd 
      --data-dir=/etcd-data --name etcd1 
      --initial-advertise-peer-urls http://0.0.0.0:2380 --listen-peer-urls http://0.0.0.0:2380 
      --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 
      --initial-cluster etcd1=http://0.0.0.0:2380
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./etcd/data:/etcd-data
    container_name: etcd
  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - 6379:6379
    volumes:
       - ./redis/data:/data
    container_name: redis