// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Gender   int    `json:"gender"`
}

type User struct {
	ID        string `json:"id"`
	Nickname  string `json:"nickname"`
	Phone     string `json:"phone"`
	Gender    int    `json:"gender"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UserConnection struct {
	TotalCount int     `json:"totalCount"`
	Edges      []*User `json:"edges"`
}
